const config = {
  AWS_REGION: 'YOUR_AWS_REGION',
  AWS_COGNITO_IDENTITY_POOL_ID: 'YOUR_ID_POOL',
  AWS_COGNITO_USER_POOL_ID: 'YOUR_USER_POOL_ID',
  AWS_COGNITO_CLIENT_ID: 'YOUR_CLIENT_ID'
};

export default config;
